language: node_js
node_js:
  - "8"
  - "10"
  - "9"
cache:
  directories:
  - node_modules
script:
  - npm run test:coverage
  # - npm run build

jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: npm install jest && jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage